use_frameworks!

platform :ios, '10.0'

target 'Polyskel_Example' do
  pod 'Polyskel', :path => '../'

  target 'Polyskel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
